movies/urls.py
from django.urls import path
from .views import MovieList, movie_search, movie_add, MovieDelete

urlpatterns = [
    path('', MovieList.as_view(), name='home'),
    path('search/', movie_search, name='movie-search'),
    path('movie-add/<str:imdb_id>', movie_add, name='movie-add'),
    path('movie-delete/<int:pk>', MovieDelete.as_view(), name="movie-delete"),
]

toBeFinished/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('movies.urls'))
]

users/urls.py
from django.urls import path
from .views import SignUpView, password_reset_request
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path("password_reset", password_reset_request, name="password_reset_start"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),

]

movies/models.py
from django.db import models
from django.conf import settings


class Movie(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    imdb_id = models.CharField(max_length=50, unique=True)
    title = models.CharField(max_length=200)
    release_date = models.CharField(max_length=15)
    runtime = models.IntegerField()
    date_added = models.DateField(auto_now_add=True)
    minutes_seen = models.IntegerField()
    is_fully_seen = models.BooleanField(default=False)
    poster_url = models.URLField()

    @property
    def minutes_seen_formatted(self):
        return f"{self.minutes_seen // 60}h {self.minutes_seen % 60}min"

    @property
    def percent_seen(self):
        return f"{round(self.minutes_seen / self.runtime * 100)}"

    @property
    def runtime_formatted(self):
        return f"{self.runtime // 60}h {self.runtime % 60}min"

    @property
    def release_year(self):
        return self.release_date[-4:]

    def __str__(self):
        return f"{self.title} ({list(self.release_date)[-1]})"

movies/forms.py
from django import forms
from .models import Movie
import re


class MovieForm(forms.Form):
    # def __init__(self, runtime):
    #     super().__init__()
    minutes_seen = forms.IntegerField(label=f'Minutes seen', min_value=0, max_value=500)
    is_fully_seen = forms.BooleanField(label='Seen fully', required=False)
    #
    # @classmethod
    # def get_form(cls, runtime):
    #     cls.minutes_seen.max_value
    #     return cls

movies/views.py
import requests
import re
from django.shortcuts import render, reverse
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy

from .models import Movie

from .forms import MovieForm

API_TOKEN = '35dfe886'


class MovieList(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Movie
    context_object_name = "movies"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movies'] = context['movies'].filter(user=self.request.user)
        return context


def movie_search(request):
    context = {}
    data = {}
    error_message = ''
    search_input = request.GET.get('search-area') or ''
    if search_input:
        query = f"http://www.omdbapi.com/?apikey={API_TOKEN}&s={search_input}&type=movie"
        response = requests.get(query).json()
        try:
            data = response['Search']

            for movie in data:  # Add field to see if user already has seen the movie
                if not Movie.objects.filter(user=request.user, imdb_id=movie["imdbID"]).exists():
                    movie["is_in_db"] = False
                else:
                    movie["is_in_db"] = True
                    obj = Movie.objects.get(user=request.user, imdb_id=movie["imdbID"])
                    movie["percent_seen"] = obj.percent_seen
                    movie["minutes_seen_formatted"] = obj.minutes_seen_formatted
                    movie["runtime_formatted"] = obj.runtime_formatted
                    movie["release_year"] = obj.release_year

        except KeyError as e:
            error_message = f"No result for '{search_input}'"

    context = {'movies': data, 'search_input': search_input, 'error_message': error_message}
    return render(request, 'movies/movie_search.html', context=context)


def movie_add(request, imdb_id):
    query = f"http://www.omdbapi.com/?apikey={API_TOKEN}&i={imdb_id}"
    data = requests.get(query).json()
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            if Movie.objects.filter(user=request.user, imdb_id=data["imdbID"]).exists():
                Movie.objects.filter(user=request.user, imdb_id=data["imdbID"]).update(
                    minutes_seen=form['minutes_seen'].value(),
                    is_fully_seen=form['is_fully_seen'].value())
            else:
                Movie.objects.create(user=request.user,
                                     imdb_id=imdb_id,
                                     title=data['Title'],
                                     release_date=data['Released'],
                                     runtime=int(re.findall(r'\d+', data['Runtime'])[0]),
                                     minutes_seen=form['minutes_seen'].value(),
                                     is_fully_seen=form['is_fully_seen'].value(),
                                     poster_url=data['Poster'])
            return HttpResponseRedirect(reverse('home'))
    else:
        if Movie.objects.filter(user=request.user, imdb_id=data["imdbID"]).exists():
            obj = Movie.objects.get(user=request.user, imdb_id=data["imdbID"])
            form = MovieForm(initial={'minutes_seen': obj.minutes_seen})
            data['exists'] = True
            data['id'] = obj.id
        else:
            form = MovieForm()
            data['exists'] = False
        form.fields['minutes_seen'].max_value = int(re.findall(r'\d+', data['Runtime'])[0])
        form.fields['minutes_seen'].widget.attrs['max'] = int(re.findall(r'\d+', data['Runtime'])[0])
        context = {'movie': data, 'form': form}

    return render(request, 'movies/movie.html', context=context)


class MovieDelete(LoginRequiredMixin, DeleteView):
    model = Movie
    success_url = reverse_lazy('home')

# class MovieUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
#     model = Movie
#     template_name = 'movies/movie.html'
#     # fields = ['minutes_seen', 'is_fully_seen']
#     success_url = reverse_lazy('home')
#     form_class = MovieForm()
#     form_class.fields['minutes_seen'].max_value = int(re.findall(r'\d+', model['Runtime'])[0])
#     form_class.fields['minutes_seen'].widget.attrs['max'] = int(re.findall(r'\d+', model['Runtime'])[0])
#
#     def test_func(self):
#         if self.request.user == self.get_object().user:
#             return True
#         else:
#             return False

movies/templates/movies/movie.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="movie-form-container">
        <img src="{{ movie.Poster }}">
        <div class="info">
            <h2>{{ movie.Title }}</h2>
            <p class="director">by {{ movie.Director }}</p>
            <div class="released">{{ movie.Released }}</div>
            <div class="runtime"><span>{{ movie.Runtime }}</span></div>
            <form method="post">
                {% csrf_token %}

                <label style="opacity: 0.8">{{ form.minutes_seen.label }}:</label>
                {{ form.minutes_seen }}
                {{ form.errors.minutes_seen }}
                <br>
                {{ form.is_fully_seen }}{{ form.is_fully_seen.label }}
                {{ form.errors.is_fully_seen }}
                <br>
                <button style="margin-bottom: 5em" class="little-button button" type="submit">
                    <i class="fa-solid fa-floppy-disk"></i> Save
                </button>
            </form>
            {% if movie.exists %}
                <a id="form-delete-button" class="button little-button" href="{% url 'movie-delete' movie.id %}"><i
                        class="fa-solid fa-trash-can"></i> Delete</a>
            {% endif %}
        </div>
    </div>
    {#    <script lang="">#}
    {#        minutes_field = document.querySelector('#id_minutes_seen')#}
    {#        minutes_info = document.querySelectorAll('.info')[1].innerText.replace( /^\D+/g, '');#}
    {#        console.log(minutes_field)#}
    {#        console.log("HI")#}
    {#        minutes_field.setAttribute('max', minutes_info)#}
    {#    </script>#}
{% endblock %}

movies/templates/movies/movie_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" style="padding: 20px">
        {% csrf_token %}
        <p style="text-align: center; color: #2568FB; margin-top: 30vh">Are you sure you want to delete "{{ movie.title }}"?</p>
        <div style="display: flex; justify-content: center">
            <button style="margin: 1em" class="button" type="submit">
                <i class="fa-solid fa-trash-can"></i> Delete
            </button>
        </div>
    </form>
{% endblock content %}

movies/templates/movies/movie_form.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="container">
        <img src="{{ movie.poster_url }}">
        <div class="info">
            <h2>{{ movie.title }}</h2>
            <p>{{ movie.release_year }}</p>
            <p>{{ movie.runtime }}min</p>
            <form method="post">
                {% csrf_token %}
                <label style="margin-top: 1em">{{ form.minutes_seen.label }}:</label>
                {{ form.minutes_seen }}
                {{ form.errors.minutes_seen }} {# how_much_seen errors #}

                <label style="margin-top: 1em">{{ form.is_fully_seen.label }}:</label>
                {{ form.is_fully_seen }}
                {{ form.errors.is_fully_seen }} {# is_fully_seen errors #}
                <input type="submit" value="Edit">
                <a class="button little-button" href="{% url 'movie-delete' movie.id %}"><i
                        class="fa-solid fa-trash-can"></i> Delete</a>
            </form>
        </div>
    </div>
{% endblock %}

movies/templates/movies/movie_list.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="add-button-wrapper">
        <a class="add-movie-button button" href="{% url 'movie-search' %}"><i class="fa-solid fa-plus"></i>Add movie</a>
    </div>
    <div class="movies-wrapper">
        {% for movie in movies %}
            {#            <div class="movie-container">#}
            {#                <img src="{{ movie.poster_url }}">#}
            {#                <div class="info">#}
            {#                    <div class="info__text">#}
            {#                        <div class="released"><span>{{ movie.release_year }}</span></div>#}
            {#                        <h2>{{ movie.title }}</h2>#}
            {#                        <div class="buttons-row">#}
            {#                            <a class="button little-button" href="{% url 'movie-add' movie.imdb_id %}"><i#}
            {#                                    class="fa-solid fa-pen-to-square"></i> Edit</a>#}
            {#                        </div>#}
            {#                    </div>#}
            {#                    <div style="width: {{ movie.percent_seen }}%" class="progress"></div>#}
            {#                </div>#}
            {#            </div>#}

            <div class="movie-container">
                <img src="{{ movie.poster_url }}" alt="{{ movie.title }}">

                <div class="info">
                    <div class="info-text">
                        <h2>{{ movie.title }}</h2>
                        <p class="released">{{ movie.release_year }}</p>
                    </div>
                    <div style="width: {{ movie.percent_seen }}%" class="progress"></div>
                    <a class="link-cancel" href="{% url 'movie-add' movie.imdb_id %}">

                        <div class="overlay">
                            <p>{{ movie.minutes_seen_formatted }} / {{ movie.runtime_formatted }}</p>
                        </div>
                    </a>
                    <a class="delete-movie-button" href="{% url 'movie-delete' movie.id %}"><i
                            class="fa-solid fa-circle-xmark"></i></a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

movies/templates/movies/movie_list1.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <a class="add-movie-button button" href="{% url 'movie-search' %}"><i class="fa-solid fa-plus"></i>Add movie</a>
    <div class="movies-wrapper">
        {% for movie in movies %}
            <div class="movie-container">
                <img src="{{ movie.poster_url }}">
                <div class="info">
                    <div class="info__text">
                        <h2>{{ movie.title }}</h2>
                        <div class="released"><span>{{ movie.release_year }}</span></div>
                        <p>{{ movie.minutes_seen_formatted }} / {{ movie.runtime_formatted }}</p>
                        <div class="buttons-row">
                            <a class="button little-button" href="{% url 'movie-add' movie.imdb_id %}"><i
                                    class="fa-solid fa-pen-to-square"></i> Edit</a>
                        </div>
                    </div>
                    <div style="width: {{ movie.percent_seen }}%" class="progress"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

movies/templates/movies/movie_search.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <form class="search-form" method="get">
        <input placeholder="Type a movie's name" type="text" name="search-area" value="{{ search_input }}">
        <button class="button" type="submit">
            <i class="fa-solid fa-magnifying-glass"></i> Search
        </button>
    </form>
    {% if not error_message %}
        <div class="movies-wrapper">
            {% for movie in movies %}
                <div class="movie-container">
                    <img src="{{ movie.Poster }}">
                    <div class="info">
                        <div class="info__text">
                            <h2>{{ movie.Title }}</h2>
                            <p  class="released">{{ movie.Year }}</p>
                            <div class="buttons-row">
                                {% if not movie.is_in_db %}
                                    <a class="button little-button" href="{% url 'movie-add' movie.imdbID %}"><i
                                            class="fa-solid fa-plus"></i> Add</a>
                                {% else %}
                                    <a class="button little-button" href="{% url 'movie-add' movie.imdbID %}"><i
                                            class="fa-solid fa-pen-to-square"></i> Edit</a>
                                {% endif %}
                            </div>
                        </div>
                        <div style="width: {{ movie.percent_seen }}%" class="progress"></div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1 style="text-align: center">
            {{ error_message }}
        </h1>
    {% endif %}
{% endblock %}